name: NNS Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-cpp-core:
    name: C++ Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DNNSCORE_BUILD_TESTS=ON -DNNSCORE_BUILD_PYTHON=OFF

    - name: Build Core Library
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure
